version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: apache-html
    ports:
      - "8080:80"
    restart: always
    
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3308"
    
  