apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
  labels:
    app: html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: septdemo.azurecr.io/htmldemo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
spec:
  type: LoadBalancer
  selector:
    app: html-app
  ports:
  - port: 80
    targetPort: 80
